# Generated by Django 4.2.9 on 2024-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPK_S', models.CharField(blank=True, max_length=255, null=True)),
                ('userPK_R', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnailPATH', models.CharField(blank=True, max_length=255, null=True)),
                ('typeNum', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('createAt', models.DateTimeField(blank=True, null=True)),
                ('createAt_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('readStatus', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('itemPK', models.CharField(blank=True, default='0', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlimTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNum', models.CharField(blank=True, max_length=255, null=True)),
                ('typeName', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
